/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package michaelShepstone;

import com.formdev.flatlaf.*;

import java.util.*;

import javax.swing.*;


/**
 *
 * @author mshep23
 */
public class DataBaseGUI_MainFrm extends javax.swing.JFrame {

    /**
     * Creates new form DataBaseGUI_MainFrm
     */
    public DataBaseGUI_MainFrm() {
        initComponents();
 
        DBmanager db = new DBmanager();

        db.connectDB();

            pnlFiltersContainer.setVisible(false);
             
        Vector allComp = db.getAllComponents();
        ComponentsLst.setListData(db.getAllComponents());

        db.disconnectDB();
        //filtersPanel.setVisible(false);

        btnDelete.setEnabled(false);
        btnEdit.setEnabled(false);
         
       
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlButtonPanner = new javax.swing.JPanel();
        btnDelete = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        BtnAdd = new javax.swing.JButton();
        BtnView = new javax.swing.JButton();
        tglFilter = new javax.swing.JToggleButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        ComponentsLst = new javax.swing.JList<>();
        pnlDetails = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        lblReleaseDate = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblSMD = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblPrice = new javax.swing.JLabel();
        lblQuantity = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        pnlFiltersContainer = new javax.swing.JPanel();
        scrFilters = new javax.swing.JScrollPane();
        pnlFilters = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        txtFilterName = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        spnQuantityMin = new javax.swing.JSpinner();
        spnQuantityMax = new javax.swing.JSpinner();
        jLabel8 = new javax.swing.JLabel();
        spnPriceMin = new javax.swing.JSpinner();
        spnPriceMax = new javax.swing.JSpinner();
        jLabel9 = new javax.swing.JLabel();
        tglFilterSMD = new javax.swing.JToggleButton();
        jLabel10 = new javax.swing.JLabel();
        dpReleaseDateFirst = new com.github.lgooddatepicker.components.DatePicker();
        jLabel11 = new javax.swing.JLabel();
        dpFilterReleaseDateLate = new com.github.lgooddatepicker.components.DatePicker();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnEdit.setText("Edit");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        BtnAdd.setText("Add");
        BtnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAddActionPerformed(evt);
            }
        });

        BtnView.setText("Refresh");
        BtnView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnViewActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlButtonPannerLayout = new javax.swing.GroupLayout(pnlButtonPanner);
        pnlButtonPanner.setLayout(pnlButtonPannerLayout);
        pnlButtonPannerLayout.setHorizontalGroup(
            pnlButtonPannerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlButtonPannerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlButtonPannerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BtnView)
                    .addComponent(BtnAdd)
                    .addComponent(btnEdit)
                    .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(42, Short.MAX_VALUE))
        );

        pnlButtonPannerLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {BtnAdd, BtnView, btnDelete, btnEdit});

        pnlButtonPannerLayout.setVerticalGroup(
            pnlButtonPannerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlButtonPannerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BtnView)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BtnAdd)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEdit)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDelete)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tglFilter.setText("Filter:");
        tglFilter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tglFilterActionPerformed(evt);
            }
        });

        ComponentsLst.setBackground(new java.awt.Color(70, 72, 75));
        ComponentsLst.setForeground(new java.awt.Color(187, 188, 187));
        ComponentsLst.setSelectionBackground(new java.awt.Color(102, 0, 255));
        ComponentsLst.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentMoved(java.awt.event.ComponentEvent evt) {
                ComponentsLstComponentMoved(evt);
            }
        });
        ComponentsLst.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                ComponentsLstValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(ComponentsLst);

        jLabel5.setText("Release Date");

        lblReleaseDate.setText("N/A");

        jLabel4.setText("SMD:");

        lblSMD.setText("N/A");

        jLabel3.setText("Price: ");

        lblPrice.setText("N/A");

        lblQuantity.setText("N/A");

        jLabel2.setText("Quantity: ");

        lblName.setText("N/A");

        jLabel1.setText("Name:");

        javax.swing.GroupLayout pnlDetailsLayout = new javax.swing.GroupLayout(pnlDetails);
        pnlDetails.setLayout(pnlDetailsLayout);
        pnlDetailsLayout.setHorizontalGroup(
            pnlDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDetailsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlDetailsLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblReleaseDate))
                    .addGroup(pnlDetailsLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblName))
                    .addGroup(pnlDetailsLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblQuantity))
                    .addGroup(pnlDetailsLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblPrice))
                    .addGroup(pnlDetailsLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblSMD)))
                .addContainerGap(115, Short.MAX_VALUE))
        );
        pnlDetailsLayout.setVerticalGroup(
            pnlDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDetailsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lblName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(lblQuantity))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(lblPrice))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(lblSMD))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(lblReleaseDate))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel6.setText("Name:");

        txtFilterName.setText("Default");
        txtFilterName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFilterNameActionPerformed(evt);
            }
        });
        txtFilterName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtFilterNameKeyPressed(evt);
            }
        });

        jLabel7.setText("Quantity:");

        spnQuantityMax.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spnQuantityMaxStateChanged(evt);
            }
        });

        jLabel8.setText("Price:");

        jLabel9.setText("SMD:");

        tglFilterSMD.setText("True");
        tglFilterSMD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tglFilterSMDActionPerformed(evt);
            }
        });

        jLabel10.setText("Release Date:");

        jLabel11.setText("TO");

        jLabel12.setText("TO");

        jLabel13.setText("TO");

        javax.swing.GroupLayout pnlFiltersLayout = new javax.swing.GroupLayout(pnlFilters);
        pnlFilters.setLayout(pnlFiltersLayout);
        pnlFiltersLayout.setHorizontalGroup(
            pnlFiltersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFiltersLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlFiltersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlFiltersLayout.createSequentialGroup()
                        .addGroup(pnlFiltersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)
                            .addGroup(pnlFiltersLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(pnlFiltersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(tglFilterSMD, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(dpReleaseDateFirst, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtFilterName, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(pnlFiltersLayout.createSequentialGroup()
                                        .addGroup(pnlFiltersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(spnPriceMin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(spnQuantityMin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(pnlFiltersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(pnlFiltersLayout.createSequentialGroup()
                                                .addComponent(jLabel12)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(spnQuantityMax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(pnlFiltersLayout.createSequentialGroup()
                                                .addComponent(jLabel13)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(spnPriceMax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                        .addContainerGap(36, Short.MAX_VALUE))
                    .addGroup(pnlFiltersLayout.createSequentialGroup()
                        .addGroup(pnlFiltersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlFiltersLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(dpFilterReleaseDateLate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel11))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        pnlFiltersLayout.setVerticalGroup(
            pnlFiltersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFiltersLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtFilterName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlFiltersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(spnQuantityMin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spnQuantityMax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlFiltersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(spnPriceMin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spnPriceMax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tglFilterSMD)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dpReleaseDateFirst, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dpFilterReleaseDateLate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        scrFilters.setViewportView(pnlFilters);

        javax.swing.GroupLayout pnlFiltersContainerLayout = new javax.swing.GroupLayout(pnlFiltersContainer);
        pnlFiltersContainer.setLayout(pnlFiltersContainerLayout);
        pnlFiltersContainerLayout.setHorizontalGroup(
            pnlFiltersContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFiltersContainerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrFilters, javax.swing.GroupLayout.DEFAULT_SIZE, 206, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlFiltersContainerLayout.setVerticalGroup(
            pnlFiltersContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFiltersContainerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrFilters, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(tglFilter))
                    .addComponent(pnlDetails, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnlButtonPanner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnlFiltersContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 24, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addGap(18, 18, 18))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pnlButtonPanner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pnlDetails, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tglFilter)
                        .addGap(18, 18, 18)
                        .addComponent(pnlFiltersContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    

    private void BtnViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnViewActionPerformed
        DBmanager db = new DBmanager();

        db.connectDB();
        
        db.displayAllComponents();
        ComponentsLst.setListData(db.getAllComponents());
        
       
        db.disconnectDB();
    }//GEN-LAST:event_BtnViewActionPerformed

    private void ComponentsLstComponentMoved(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_ComponentsLstComponentMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_ComponentsLstComponentMoved

    private void tglFilterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tglFilterActionPerformed
if(!pnlFiltersContainer.isVisible()){
    pnlFiltersContainer.setVisible(true);
    System.out.println("TRUE");
    pnlFiltersContainer.setVisible(true);
}else{
    pnlFiltersContainer.setVisible(false);
}



        // TODO add your handling code here:
      /*  if (!filtersPanel.isShowing()) {
            filtersPanel.setVisible(true);
        } else {
            filtersPanel.setVisible(false);
        }*/
    }//GEN-LAST:event_tglFilterActionPerformed

    private void ComponentsLstValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_ComponentsLstValueChanged
        //System.out.println("Changed");

//         System.out.println(((Component)ComponentsLst.getSelectedValue()).getComponentPrice());
        if (ComponentsLst.getSelectedIndex() != -1) {
            lblName.setText(((Component) ComponentsLst.getSelectedValue()).getComponentName());
            lblPrice.setText("" + ((Component) ComponentsLst.getSelectedValue()).getComponentPrice());
            lblQuantity.setText("" + ((Component) ComponentsLst.getSelectedValue()).getComponentQuantity());
            lblReleaseDate.setText("" + ((Component) ComponentsLst.getSelectedValue()).getReleaseDate());
            lblSMD.setText("" + ((Component) ComponentsLst.getSelectedValue()).isSMD());

            btnEdit.setEnabled(true);
            btnDelete.setEnabled(true);
            
        }
    }//GEN-LAST:event_ComponentsLstValueChanged

    private void BtnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAddActionPerformed

        new frmAddComponent().setVisible(true);
//Hello

        this.dispose();
// TODO add your handling code here:
    }//GEN-LAST:event_BtnAddActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        if (ComponentsLst.getSelectedIndex() == -1) {

            System.out.println("Nothing is selected");

        } else {
            new frmEditComponent((Component) ComponentsLst.getSelectedValue()).setVisible(true);
                
            this.dispose();

        }


    }//GEN-LAST:event_btnEditActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed

        if (ComponentsLst.getSelectedIndex() == -1) {

            System.out.println("Nothing is selected");

        } else {
            //   ).setVisible(true);
            Component selected = (Component) ComponentsLst.getSelectedValue();

//Window to ask if the object is to be deleted, 0 is yes, 1 is no
            int option = JOptionPane.showConfirmDialog(null, "Are you sure you want to delete \"" + selected.getComponentName() + "\"?\nThis action is very permanent and cannot be undone.", "DELETE", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);

            System.out.println(option);

            //logic connected to previous lines
            if (option == 0) {

                DBmanager db = new DBmanager();
                System.out.println("Deleting component");
                db.deleateComponent(selected);
                System.out.println("About to refresh");
                refresh();
            }

        }


    }//GEN-LAST:event_btnDeleteActionPerformed

    private void tglFilterSMDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tglFilterSMDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tglFilterSMDActionPerformed

    private void txtFilterNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFilterNameActionPerformed
       
    }//GEN-LAST:event_txtFilterNameActionPerformed

    
    
    
    Component searchComponent = new Component();
    
    
    private void spnQuantityMaxStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spnQuantityMaxStateChanged
   searchComponent.setComponentQuantity(spnPriceMax.getValue());
    }//GEN-LAST:event_spnQuantityMaxStateChanged

    private void txtFilterNameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFilterNameKeyPressed
            searchComponent.setComponentName(txtFilterName.getText());
    }//GEN-LAST:event_txtFilterNameKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
      UIManager.installLookAndFeel("FlatLaFDark", "com.formdev.flatlaf.FlatDarkLaf");
        
        
        for(int i = 0; i  <UIManager.getInstalledLookAndFeels().length; i++){
            System.out.println(i +"/"+UIManager.getInstalledLookAndFeels().length);
            
            System.out.println(UIManager.getInstalledLookAndFeels()[i].getName());
        
            
            
              
            //  javax.swing.UIManager.LookAndFeelInfo info  javax.swing.UIManager.getInstalledLookAndFeels() 
            try{
            if("FlatLaFDark".equalsIgnoreCase(UIManager.getInstalledLookAndFeels()[i].getName())){
              System.out.println(UIManager.getInstalledLookAndFeels()[i].getClassName());
             FlatDarkLaf.setup();
             
          UIManager.setLookAndFeel(UIManager.getInstalledLookAndFeels()[i].getClassName());
          
         // javax.swing.UIManager.setLookAndFeel
              System.out.println("Class Found");
          
            }
          }catch( ClassNotFoundException e){
              
              System.out.println("Not Found");
              
          } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DataBaseGUI_MainFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DataBaseGUI_MainFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DataBaseGUI_MainFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
            
        }
        //</editor-fold>
      
     
        //Create and display the form */
          //"com.formdev.flatlaf.intellijthemes.FlatDarkFlatIJTheme";
          
          // UIManager.installLookAndFeel("FlatLaFDark", com.formdev.flatlaf.intellijthemes.FlatDarkFlatIJTheme);
         
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DataBaseGUI_MainFrm().setVisible(true);

            }
        });
    }

    public void refresh() {

        DBmanager db = new DBmanager();

        db.connectDB();
        System.out.println("REFRESHED 1 / 3");

        ComponentsLst.setListData(db.getAllComponents());

        db.disconnectDB();

        System.out.println("REFRESHED  2 / 3");
       // filtersPanel.setVisible(false);

        btnDelete.setEnabled(false);
        btnEdit.setEnabled(false);
        System.out.println("REFRESHED 3 / 3");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAdd;
    private javax.swing.JButton BtnView;
    private javax.swing.JList<Object> ComponentsLst;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnEdit;
    private com.github.lgooddatepicker.components.DatePicker dpFilterReleaseDateLate;
    private com.github.lgooddatepicker.components.DatePicker dpReleaseDateFirst;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblPrice;
    private javax.swing.JLabel lblQuantity;
    private javax.swing.JLabel lblReleaseDate;
    private javax.swing.JLabel lblSMD;
    private javax.swing.JPanel pnlButtonPanner;
    private javax.swing.JPanel pnlDetails;
    private javax.swing.JPanel pnlFilters;
    private javax.swing.JPanel pnlFiltersContainer;
    private javax.swing.JScrollPane scrFilters;
    private javax.swing.JSpinner spnPriceMax;
    private javax.swing.JSpinner spnPriceMin;
    private javax.swing.JSpinner spnQuantityMax;
    private javax.swing.JSpinner spnQuantityMin;
    private javax.swing.JToggleButton tglFilter;
    private javax.swing.JToggleButton tglFilterSMD;
    private javax.swing.JTextField txtFilterName;
    // End of variables declaration//GEN-END:variables
}
