/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package michaelShepstone;

import com.formdev.flatlaf.*;

import java.util.*;

import javax.swing.*;


/**
 *
 * @author mshep23
 */
public class DataBaseGUI_MainFrm extends javax.swing.JFrame {

    /**
     * Creates new form DataBaseGUI_MainFrm
     */
    public DataBaseGUI_MainFrm() {
        initComponents();
 
        DBmanager db = new DBmanager();

        db.connectDB();

             scrFilters.setVisible(false);
             
       // Vector allComp = db.getAllComponents();
        
        
        Vector allComp = db.getAllComponents();
        ComponentsLst.setListData(db.getAllComponents());

        db.disconnectDB();
        //filtersPanel.setVisible(false);

        btnDelete.setEnabled(false);
        btnEdit.setEnabled(false);
        

         btnFilter.setVisible(false);
       lblFilters.setVisible(false);
       lblFilters2.setVisible(false);
       lblFilters3.setVisible(false);
       
       

       
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlButtonPanner = new javax.swing.JPanel();
        btnDelete = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        BtnAdd = new javax.swing.JButton();
        BtnView = new javax.swing.JButton();
        tglFilter = new javax.swing.JToggleButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        ComponentsLst = new javax.swing.JList<>();
        pnlDetails = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        lblReleaseDate = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblSMD = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblPrice = new javax.swing.JLabel();
        lblQuantity = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        pnlFiltersContainer = new javax.swing.JPanel();
        scrFilters = new javax.swing.JScrollPane();
        pnlFilters = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        txtFilterName = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        spnQuantityMin = new javax.swing.JSpinner();
        spnQuantityMax = new javax.swing.JSpinner();
        jLabel8 = new javax.swing.JLabel();
        spnPriceMin = new javax.swing.JSpinner();
        spnPriceMax = new javax.swing.JSpinner();
        jLabel9 = new javax.swing.JLabel();
        tglFilterSMD = new javax.swing.JToggleButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        btnFilter = new javax.swing.JButton();
        lblFilters = new javax.swing.JLabel();
        lblFilters2 = new javax.swing.JLabel();
        lblFilters3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        btnDelete.setText("Delete");
        btnDelete.setToolTipText("Delete a component");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnEdit.setText("Edit");
        btnEdit.setToolTipText("Edit a new Component\n");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        BtnAdd.setText("Add");
        BtnAdd.setToolTipText("Add a new component\n");
        BtnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAddActionPerformed(evt);
            }
        });

        BtnView.setText("Refresh");
        BtnView.setToolTipText("Refresh the list");
        BtnView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnViewActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlButtonPannerLayout = new javax.swing.GroupLayout(pnlButtonPanner);
        pnlButtonPanner.setLayout(pnlButtonPannerLayout);
        pnlButtonPannerLayout.setHorizontalGroup(
            pnlButtonPannerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlButtonPannerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlButtonPannerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BtnView)
                    .addComponent(BtnAdd)
                    .addComponent(btnEdit)
                    .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(42, Short.MAX_VALUE))
        );

        pnlButtonPannerLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {BtnAdd, BtnView, btnDelete, btnEdit});

        pnlButtonPannerLayout.setVerticalGroup(
            pnlButtonPannerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlButtonPannerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BtnView)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BtnAdd)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEdit)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDelete)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tglFilter.setText("Filter:");
        tglFilter.setToolTipText("Display the filter menu\n");
        tglFilter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tglFilterActionPerformed(evt);
            }
        });

        ComponentsLst.setBackground(new java.awt.Color(70, 72, 75));
        ComponentsLst.setForeground(new java.awt.Color(187, 188, 187));
        ComponentsLst.setSelectionBackground(new java.awt.Color(102, 0, 255));
        ComponentsLst.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentMoved(java.awt.event.ComponentEvent evt) {
                ComponentsLstComponentMoved(evt);
            }
        });
        ComponentsLst.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                ComponentsLstValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(ComponentsLst);

        jLabel5.setText("Release Date");

        lblReleaseDate.setText("N/A");

        jLabel4.setText("SMD:");

        lblSMD.setText("N/A");

        jLabel3.setText("Price: ");

        lblPrice.setText("N/A");

        lblQuantity.setText("N/A");

        jLabel2.setText("Quantity: ");

        lblName.setText("N/A");

        jLabel1.setText("Name:");

        javax.swing.GroupLayout pnlDetailsLayout = new javax.swing.GroupLayout(pnlDetails);
        pnlDetails.setLayout(pnlDetailsLayout);
        pnlDetailsLayout.setHorizontalGroup(
            pnlDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDetailsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlDetailsLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblReleaseDate))
                    .addGroup(pnlDetailsLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblName))
                    .addGroup(pnlDetailsLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblQuantity))
                    .addGroup(pnlDetailsLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblPrice))
                    .addGroup(pnlDetailsLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblSMD)))
                .addContainerGap(115, Short.MAX_VALUE))
        );
        pnlDetailsLayout.setVerticalGroup(
            pnlDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDetailsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lblName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(lblQuantity))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(lblPrice))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(lblSMD))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(lblReleaseDate))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel6.setText("Name:");

        txtFilterName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFilterNameActionPerformed(evt);
            }
        });
        txtFilterName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtFilterNameKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtFilterNameKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtFilterNameKeyTyped(evt);
            }
        });

        jLabel7.setText("Quantity:");

        spnQuantityMin.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spnQuantityMinStateChanged(evt);
            }
        });
        spnQuantityMin.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                spnQuantityMinKeyReleased(evt);
            }
        });

        spnQuantityMax.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spnQuantityMaxStateChanged(evt);
            }
        });
        spnQuantityMax.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                spnQuantityMaxKeyReleased(evt);
            }
        });

        jLabel8.setText("Price:");

        spnPriceMin.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spnPriceMinStateChanged(evt);
            }
        });
        spnPriceMin.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                spnPriceMinKeyReleased(evt);
            }
        });

        spnPriceMax.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spnPriceMaxStateChanged(evt);
            }
        });
        spnPriceMax.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                spnPriceMaxKeyReleased(evt);
            }
        });

        jLabel9.setText("SMD:");

        tglFilterSMD.setText("NOT SELECTED");
        tglFilterSMD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tglFilterSMDActionPerformed(evt);
            }
        });

        jLabel12.setText("TO");

        jLabel13.setText("TO");

        javax.swing.GroupLayout pnlFiltersLayout = new javax.swing.GroupLayout(pnlFilters);
        pnlFilters.setLayout(pnlFiltersLayout);
        pnlFiltersLayout.setHorizontalGroup(
            pnlFiltersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFiltersLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlFiltersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addGroup(pnlFiltersLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(pnlFiltersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtFilterName, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pnlFiltersLayout.createSequentialGroup()
                                .addGroup(pnlFiltersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(spnPriceMin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(spnQuantityMin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(pnlFiltersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(pnlFiltersLayout.createSequentialGroup()
                                        .addComponent(jLabel12)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(spnQuantityMax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(pnlFiltersLayout.createSequentialGroup()
                                        .addComponent(jLabel13)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(spnPriceMax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(tglFilterSMD, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        pnlFiltersLayout.setVerticalGroup(
            pnlFiltersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFiltersLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtFilterName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlFiltersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(spnQuantityMin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spnQuantityMax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlFiltersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(spnPriceMin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spnPriceMax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tglFilterSMD)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        scrFilters.setViewportView(pnlFilters);

        javax.swing.GroupLayout pnlFiltersContainerLayout = new javax.swing.GroupLayout(pnlFiltersContainer);
        pnlFiltersContainer.setLayout(pnlFiltersContainerLayout);
        pnlFiltersContainerLayout.setHorizontalGroup(
            pnlFiltersContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFiltersContainerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrFilters, javax.swing.GroupLayout.DEFAULT_SIZE, 206, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlFiltersContainerLayout.setVerticalGroup(
            pnlFiltersContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFiltersContainerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrFilters, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnFilter.setText("Update Filters");
        btnFilter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFilterActionPerformed(evt);
            }
        });

        lblFilters.setText("Values left blank");

        lblFilters2.setText("or set to 0");

        lblFilters3.setText("will be ignored");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(tglFilter))
                    .addComponent(pnlDetails, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnlButtonPanner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pnlFiltersContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnFilter)
                            .addComponent(lblFilters)
                            .addComponent(lblFilters2)
                            .addComponent(lblFilters3))))
                .addGap(0, 4, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addGap(18, 18, 18))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pnlButtonPanner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pnlDetails, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tglFilter)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(pnlFiltersContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblFilters)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblFilters2)
                                .addGap(5, 5, 5)
                                .addComponent(lblFilters3)
                                .addGap(18, 18, 18)
                                .addComponent(btnFilter)
                                .addGap(17, 17, 17))))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void BtnViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnViewActionPerformed
        DBmanager db = new DBmanager();

        db.connectDB();

        db.displayAllComponents();
        ComponentsLst.setListData(db.getAllComponents());
        db.disconnectDB();
    }//GEN-LAST:event_BtnViewActionPerformed

    private void ComponentsLstComponentMoved(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_ComponentsLstComponentMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_ComponentsLstComponentMoved

    private void tglFilterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tglFilterActionPerformed


if(tglFilter.isSelected()){
    
    //System.out.println("FILTER SHOWING");
    scrFilters.setVisible(true);
    pnlFiltersContainer.setVisible(true);
    ////System.out.println("TRUE");
    pnlFiltersContainer.setVisible(true);
   // btnFilter.setVisible(true);
       lblFilters.setVisible(true);
       lblFilters2.setVisible(true);
       lblFilters3.setVisible(true);
}else{
    //System.out.println("FILTER NOT SHOWING");
    pnlFiltersContainer.setVisible(false);
    btnFilter.setVisible(false);
       lblFilters.setVisible(false);
       lblFilters2.setVisible(false);
       lblFilters3.setVisible(false);

}



        // TODO add your handling code here:
      /*  if (!filtersPanel.isShowing()) {
            filtersPanel.setVisible(true);
        } else {
            filtersPanel.setVisible(false);
        }*/
    }//GEN-LAST:event_tglFilterActionPerformed

    private void ComponentsLstValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_ComponentsLstValueChanged
        ////System.out.println("Changed");

//         //System.out.println(((Component)ComponentsLst.getSelectedValue()).getComponentPrice());
        if (ComponentsLst.getSelectedIndex() != -1) {
            lblName.setText(((Component) ComponentsLst.getSelectedValue()).getComponentName());
            lblPrice.setText("" + ((Component) ComponentsLst.getSelectedValue()).getComponentPrice());
            lblQuantity.setText("" + ((Component) ComponentsLst.getSelectedValue()).getComponentQuantity());
            lblReleaseDate.setText("" + ((Component) ComponentsLst.getSelectedValue()).getReleaseDate());
            lblSMD.setText("" + ((Component) ComponentsLst.getSelectedValue()).isSMD());

            btnEdit.setEnabled(true);
            btnDelete.setEnabled(true);
            
        }
    }//GEN-LAST:event_ComponentsLstValueChanged

    private void BtnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAddActionPerformed

        new frmAddComponent().setVisible(true);
//Hello

        this.dispose();
// TODO add your handling code here:
    }//GEN-LAST:event_BtnAddActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        if (ComponentsLst.getSelectedIndex() == -1) {

            //System.out.println("Nothing is selected");

        } else {
            new frmEditComponent((Component) ComponentsLst.getSelectedValue()).setVisible(true);
                
            this.dispose();

        }


    }//GEN-LAST:event_btnEditActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed

        if (ComponentsLst.getSelectedIndex() == -1) {

            //System.out.println("Nothing is selected");

        } else {
            //   ).setVisible(true);
            Component selected = (Component) ComponentsLst.getSelectedValue();

//Window to ask if the object is to be deleted, 0 is yes, 1 is no
            int option = JOptionPane.showConfirmDialog(null, "Are you sure you want to delete \"" + selected.getComponentName() + "\"?\nThis action is very permanent and cannot be undone.", "DELETE", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);

            //System.out.println(option);

            //logic connected to previous lines
            if (option == 0) {

                DBmanager db = new DBmanager();
                //System.out.println("Deleting component");
                db.deleateComponent(selected);
                //System.out.println("About to refresh");
                refresh();
            }

        }


    }//GEN-LAST:event_btnDeleteActionPerformed


    private void jToggleButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton2ActionPerformed


    String where = "";
    String sqlName = "";
    String sqlMaxQ = "";
    String sqlMinQ = "";
    String sqlMaxP = "";
    String sqlMinP = "";
    String sqlSMD = "";
    
    
            
         
    
    private void tglFilterSMDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tglFilterSMDActionPerformed
        if(tglFilterSMD.isSelected()){
            tglFilterSMD.setText("TRUE");
            
            
            
            
            
        }else{
            
            tglFilterSMD.setText("FALSE");
            
        }
        updateFilterResult();
       
    }//GEN-LAST:event_tglFilterSMDActionPerformed

    private void txtFilterNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFilterNameActionPerformed
updateFilterResult();
    }//GEN-LAST:event_txtFilterNameActionPerformed

    private void spnQuantityMaxStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spnQuantityMaxStateChanged
  updateFilterResult();
    }//GEN-LAST:event_spnQuantityMaxStateChanged

    private void txtFilterNameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFilterNameKeyPressed
    updateFilterResult();
    }//GEN-LAST:event_txtFilterNameKeyPressed

    
    void updateFilterResult(){
        
        
         boolean multipleFilters = false;
         String where = "";
    String sqlName = "";
    String sqlMaxQ = "";
    String sqlMinQ = "";
    String sqlMaxP = "";
    String sqlMinP = "";
    String sqlSMD = "";

  //System.out.println("Multiple Filters: " + multipleFilters);
  //System.out.println("SQL MAX QUANTITY: "+sqlMaxQ);
  
  
      

        if(!(txtFilterName.getText().isBlank())){
        sqlName = " ComponentName LIKE '*"+txtFilterName.getText()+"*' ";
   multipleFilters = true;
    
    }else{
        
        sqlName = "";
    }
        
        
    if((int)spnPriceMax.getValue() != 0){
        
        if(multipleFilters){
            
            sqlMaxP = " AND ";
        }
        sqlMaxP += " ComponentPrice <= " + (int) spnPriceMax.getValue();
        multipleFilters = true;
    }else{
        
        sqlMaxP = "";
    }
   
    if((int)spnPriceMin.getValue() != 0){
        
        if(multipleFilters){
            
            sqlMinP = " AND ";
        }
        sqlMinP += " ComponentPrice >= " + (int) spnPriceMin.getValue();
        multipleFilters = true;
    }else{
        
        sqlMinP = "";
    }
   
    


    if((int)spnQuantityMax.getValue() != 0){
        //System.out.println(sqlMaxQ);
        //System.out.println(multipleFilters);
          if(multipleFilters){
            
            sqlMaxQ = " AND ";
        }
        sqlMaxQ += " ComponentQuantity <= " + (int)spnQuantityMax.getValue();
        multipleFilters = true;
        //System.out.println(sqlMaxQ);
    }else{
        
        sqlMaxQ = "";
    }
   
    
    if((int)spnQuantityMin.getValue() != 0){
          if(multipleFilters){
            
            sqlMinQ = " AND ";
        }
        sqlMinQ += " ComponentQuantity >= " + (int)spnQuantityMin.getValue();
        multipleFilters = true;
        
    }else{
        
        sqlMinQ = "";
    }
   
    if(!(tglFilterSMD.getText().equalsIgnoreCase("NOT SELECTED"))){
        
         if(multipleFilters){
            
            sqlSMD = " AND ";
        }
        if(tglFilterSMD.isSelected()){
            sqlSMD += " SMD = TRUE";
        }else{
             sqlSMD += " SMD = FALSE";
        }
         multipleFilters = true;
    }else{
        
        sqlSMD = "";
    }
   
    
          //System.out.println("Multiple Filters" + multipleFilters);
                
                if(multipleFilters){
                
                String SQLFinal = "SELECT * FROM tblComponents WHERE " + where +sqlName+sqlMaxQ+sqlMinQ+sqlMaxP+sqlMinP+sqlSMD;
                System.out.println(SQLFinal);
                
                 DBmanager db = new DBmanager();

        db.connectDB();
        
       
        ComponentsLst.setListData(db.getSearch(SQLFinal));
        
       
        db.disconnectDB();
                
                }
    }
    private void spnQuantityMinStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spnQuantityMinStateChanged
       updateFilterResult();   // TODO add your handling code here:
    }//GEN-LAST:event_spnQuantityMinStateChanged

    private void txtFilterNameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFilterNameKeyReleased
        updateFilterResult();
    }//GEN-LAST:event_txtFilterNameKeyReleased

    private void btnFilterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFilterActionPerformed
        updateFilterResult();

        boolean multipleFilters = false;
        String where = "";
        String sqlName = "";
        String sqlMaxQ = "";
        String sqlMinQ = "";
        String sqlMaxP = "";
        String sqlMinP = "";
        String sqlSMD = "";

        if(!(txtFilterName.getText().isBlank())){
            sqlName = " ComponentName LIKE '*"+txtFilterName.getText()+"*' ";
            multipleFilters = true;

        }else{

            sqlName = "";
        }

        if((int)spnPriceMax.getValue() != 0){

            if(multipleFilters){

                sqlMaxP = " AND ";
            }
            sqlMaxP += " ComponentPrice <= " + (int) spnPriceMax.getValue();
            multipleFilters = true;
        }else{

            sqlMaxP = "";
        }

        if((int)spnPriceMin.getValue() != 0){

            if(multipleFilters){

                sqlMinP = " AND ";
            }
            sqlMinP += " ComponentPrice >= " + (int) spnPriceMin.getValue();
            multipleFilters = true;
        }else{

            sqlMinP = "";
        }

        if((int)spnQuantityMax.getValue() != 0){
            if(multipleFilters){

                sqlMaxQ = " AND ";
            }
            sqlMaxQ += " ComponentQuantity <= " + (int)spnQuantityMax.getValue();
            multipleFilters = true;

        }else{

            sqlMaxQ = "";
        }

        if((int)spnQuantityMin.getValue() != 0){
            if(multipleFilters){

                sqlMinQ = " AND ";
            }
            sqlMinQ += " ComponentQuantity >= " + (int)spnQuantityMin.getValue();
            multipleFilters = true;

        }else{

            sqlMinQ = "";
        }

        if(!(tglFilterSMD.getText().equalsIgnoreCase("NOT SELECTED"))){

            if(multipleFilters){

                sqlSMD = " AND ";
            }
            if(tglFilterSMD.isSelected()){
                sqlSMD += " SMD = TRUE";
            }else{
                sqlSMD += " SMD = FALSE";
            }
            multipleFilters = true;
        }else{

            sqlSMD = "";
        }

        if(!(txtFilterName.getText().isBlank())){
            sqlName = " ComponentName LIKE '*"+txtFilterName.getText()+"*' ";
            multipleFilters = true;

        }else{

            sqlName = "";
        }

        if((int)spnPriceMax.getValue() != 0){

            if(multipleFilters){

                sqlMaxP = " AND ";
            }
            sqlMaxP += " ComponentPrice <= " + (int) spnPriceMax.getValue();
            multipleFilters = true;
        }else{

            sqlMaxP = "";
        }

        if((int)spnPriceMin.getValue() != 0){

            if(multipleFilters){

                sqlMinP = " AND ";
            }
            sqlMinP += " ComponentPrice >= " + (int) spnPriceMin.getValue();
            multipleFilters = true;
        }else{

            sqlMinP = "";
        }

        if((int)spnQuantityMax.getValue() != 0){
            if(multipleFilters){

                sqlMaxQ = " AND ";
            }
            sqlMaxQ += " ComponentQuantity <= " + (int)spnQuantityMax.getValue();
            multipleFilters = true;

        }else{

            sqlMaxQ = "";
        }

        if((int)spnQuantityMin.getValue() != 0){
            if(multipleFilters){

                sqlMinQ = " AND ";
            }
            sqlMinQ += " ComponentQuantity >= " + (int)spnQuantityMin.getValue();
            multipleFilters = true;

        }else{

            sqlMinQ = "";
        }

        if(!(tglFilterSMD.getText().equalsIgnoreCase("NOT SELECTED"))){

            if(multipleFilters){

                sqlSMD = " AND ";
            }
            if(tglFilterSMD.isSelected()){
                sqlSMD += " SMD = TRUE";
            }else{
                sqlSMD += " SMD = FALSE";
            }
            multipleFilters = true;
        }else{

            sqlSMD = "";
        }

        //System.out.println(multipleFilters);

        if(multipleFilters){

            String SQLFinal = "SELECT * FROM tblComponents WHERE " + where +sqlName+sqlMaxQ+sqlMinQ+sqlMaxP+sqlMinP+sqlSMD;
            System.out.println(SQLFinal);

            DBmanager db = new DBmanager();

            db.connectDB();

            ComponentsLst.setListData(db.getSearch(SQLFinal));

            db.disconnectDB();

        }
    }//GEN-LAST:event_btnFilterActionPerformed

    private void spnPriceMinStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spnPriceMinStateChanged
updateFilterResult();        // TODO add your handling code here:
    }//GEN-LAST:event_spnPriceMinStateChanged

    private void spnPriceMaxStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spnPriceMaxStateChanged
updateFilterResult();        // TODO add your handling code here:
    }//GEN-LAST:event_spnPriceMaxStateChanged

    private void spnQuantityMinKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_spnQuantityMinKeyReleased
updateFilterResult();        // TODO add your handling code here:
    }//GEN-LAST:event_spnQuantityMinKeyReleased

    private void spnQuantityMaxKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_spnQuantityMaxKeyReleased
updateFilterResult();         // TODO add your handling code here:
    }//GEN-LAST:event_spnQuantityMaxKeyReleased

    private void spnPriceMinKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_spnPriceMinKeyReleased
updateFilterResult();         // TODO add your handling code here:
    }//GEN-LAST:event_spnPriceMinKeyReleased

    private void spnPriceMaxKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_spnPriceMaxKeyReleased
updateFilterResult();         // TODO add your handling code here:
    }//GEN-LAST:event_spnPriceMaxKeyReleased

    private void txtFilterNameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFilterNameKeyTyped
updateFilterResult();        // TODO add your handling code here:
    }//GEN-LAST:event_txtFilterNameKeyTyped



    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
      UIManager.installLookAndFeel("FlatLaFDark", "com.formdev.flatlaf.FlatDarkLaf");
        
        
        for(int i = 0; i  <UIManager.getInstalledLookAndFeels().length; i++){
            //System.out.println(i +"/"+UIManager.getInstalledLookAndFeels().length);
            
            //System.out.println(UIManager.getInstalledLookAndFeels()[i].getName());
        
            
            
              
            //  javax.swing.UIManager.LookAndFeelInfo info  javax.swing.UIManager.getInstalledLookAndFeels() 
            try{
            if("FlatLaFDark".equalsIgnoreCase(UIManager.getInstalledLookAndFeels()[i].getName())){
              //System.out.println(UIManager.getInstalledLookAndFeels()[i].getClassName());
             FlatDarkLaf.setup();
             
          UIManager.setLookAndFeel(UIManager.getInstalledLookAndFeels()[i].getClassName());
          
         // javax.swing.UIManager.setLookAndFeel
              //System.out.println("Class Found");
          
            }
          }catch( ClassNotFoundException e){
              
              //System.out.println("Not Found");
              
          } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DataBaseGUI_MainFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DataBaseGUI_MainFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DataBaseGUI_MainFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
            
        }
        //</editor-fold>
      
     
        //Create and display the form */
          //"com.formdev.flatlaf.intellijthemes.FlatDarkFlatIJTheme";
          
          // UIManager.installLookAndFeel("FlatLaFDark", com.formdev.flatlaf.intellijthemes.FlatDarkFlatIJTheme);
         
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DataBaseGUI_MainFrm().setVisible(true);

            }
        });
    }

    public void refresh() {

        DBmanager db = new DBmanager();

        db.connectDB();
        //System.out.println("REFRESHED 1 / 3");

        ComponentsLst.setListData(db.getAllComponents());

        db.disconnectDB();

        //System.out.println("REFRESHED  2 / 3");
       // filtersPanel.setVisible(false);

        btnDelete.setEnabled(false);
        btnEdit.setEnabled(false);
        //System.out.println("REFRESHED 3 / 3");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAdd;
    private javax.swing.JButton BtnView;
    private javax.swing.JList<Object> ComponentsLst;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnFilter;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblFilters;
    private javax.swing.JLabel lblFilters2;
    private javax.swing.JLabel lblFilters3;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblPrice;
    private javax.swing.JLabel lblQuantity;
    private javax.swing.JLabel lblReleaseDate;
    private javax.swing.JLabel lblSMD;
    private javax.swing.JPanel pnlButtonPanner;
    private javax.swing.JPanel pnlDetails;
    private javax.swing.JPanel pnlFilters;
    private javax.swing.JPanel pnlFiltersContainer;
    private javax.swing.JScrollPane scrFilters;
    private javax.swing.JSpinner spnPriceMax;
    private javax.swing.JSpinner spnPriceMin;
    private javax.swing.JSpinner spnQuantityMax;
    private javax.swing.JSpinner spnQuantityMin;
    private javax.swing.JToggleButton tglFilter;
    private javax.swing.JToggleButton tglFilterSMD;
    private javax.swing.JTextField txtFilterName;
    // End of variables declaration//GEN-END:variables
}
