/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package michaelShepstone;

import com.formdev.flatlaf.FlatDarkLaf;
import java.time.LocalDate;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.*;

/**
 *
 * @author mshep23
 */
public class frmAddComponent extends javax.swing.JFrame {

    /**
     * Creates new form frmAddComponent
     */
    public frmAddComponent() {
        initComponents();
        this.setTitle("Electronic Component Manager - Add Component");
        //Hides the error messages from the user
        lblGeneralError.setVisible(false);
        lblDateError.setVisible(false);
        lblNameError.setVisible(false);
        dpReleaseDate.repaint();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtcomponentName = new javax.swing.JTextField();
        dpReleaseDate = new com.github.lgooddatepicker.components.DatePicker();
        spnQuantity = new javax.swing.JSpinner();
        spnPrice = new javax.swing.JSpinner();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tglSMD = new javax.swing.JToggleButton();
        btnSubmit = new javax.swing.JButton();
        lblNameError = new javax.swing.JLabel();
        lblGeneralError = new javax.swing.JLabel();
        lblDateError = new javax.swing.JLabel();
        btnClose = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtcomponentName.setText("Default");
        txtcomponentName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcomponentNameActionPerformed(evt);
            }
        });

        dpReleaseDate.setBackground(new java.awt.Color(51, 51, 51));
        dpReleaseDate.setForeground(new java.awt.Color(0, 0, 204));

        spnQuantity.setModel(new javax.swing.SpinnerNumberModel(1, 0, null, 1));

        spnPrice.setModel(new javax.swing.SpinnerNumberModel(0.0d, 0.0d, null, 0.0d));

        jLabel1.setText("Component Name");

        jLabel2.setText("Component Quantity");

        jLabel3.setText("Component Price");

        jLabel4.setText("SMD:");

        jLabel5.setText("Release Date");

        tglSMD.setText("False");
        tglSMD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tglSMDActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtcomponentName, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tglSMD)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(spnQuantity, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(spnPrice, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(dpReleaseDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {dpReleaseDate, spnPrice, spnQuantity, tglSMD, txtcomponentName});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtcomponentName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(spnQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(spnPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tglSMD))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(dpReleaseDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnSubmit.setText("Submit");
        btnSubmit.setToolTipText("Add the component to the databse");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });

        lblNameError.setText("This must not be left blank");
        lblNameError.setForeground(new java.awt.Color(255, 0, 0));

        lblGeneralError.setText("There is one or more erros preventing you from submitting");
        lblGeneralError.setForeground(new java.awt.Color(255, 0, 0));

        lblDateError.setText("This is not a valid date");
        lblDateError.setForeground(new java.awt.Color(255, 0, 0));

        btnClose.setText("Close");
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 28, Short.MAX_VALUE)
                                .addComponent(lblNameError))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblDateError)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblGeneralError)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSubmit)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnClose)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(lblNameError)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblDateError)
                        .addGap(14, 14, 14)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSubmit)
                    .addComponent(btnClose)
                    .addComponent(lblGeneralError))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
//if the submit button is pressed, this code runs

//Updates the necessary variables
        String componentName = txtcomponentName.getText();
        int componentQuantity = (int) spnQuantity.getValue();
        double componentPrice = (double) spnPrice.getValue();
        boolean SMD = tglSMD.isSelected();
        LocalDate releaseDate = dpReleaseDate.getDate();
        
        
        //create  a new component to send to the DB manager 
        Component returnComponent = new Component(componentName, componentPrice, componentQuantity, SMD, releaseDate);

        DBmanager db = new DBmanager();
        
        //Set all the warning labels to invisible. This will allow them to dissaper ahwen the user fixes them one by one
        lblDateError.setVisible(false);
        lblGeneralError.setVisible(false);
        lblNameError.setVisible(false);
          if( JOptionPane.showConfirmDialog(null, "Would you like to add the following component?\nNAME: "+returnComponent.getComponentName()+"\nQUANTITY: "+returnComponent.getComponentQuantity()+"\nPRICE: "+returnComponent.getComponentPrice()+"\nSMD: "+returnComponent.isSMD()+"\nRELEASE DATE: "+returnComponent.getReleaseDate(), "ADD COMPONENT?", JOptionPane.YES_NO_OPTION)==0){
                new DataBaseGUI_MainFrm().setVisible(true);
        
        this.dispose();
                
                
            }
        //logic to ensure that all the fields required for the database are working
        if(db.addComponent(returnComponent) && !componentName.isBlank()){
       
          
        }
        
        else if(!db.addComponent(returnComponent)){
            lblGeneralError.setVisible(true);
        if(componentName.isBlank()){
            lblNameError.setVisible(true);
            
        }
        
        if(releaseDate == null){
            lblDateError.setVisible(true);
        }
        
        
        }
        
        

    }//GEN-LAST:event_btnSubmitActionPerformed

    private void txtcomponentNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcomponentNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcomponentNameActionPerformed

    private void tglSMDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tglSMDActionPerformed
       if(tglSMD.isSelected()){
           tglSMD.setText("TRUE");
       }else{
           tglSMD.setText("FALSE");
       }
    }//GEN-LAST:event_tglSMDActionPerformed

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
     new DataBaseGUI_MainFrm().setVisible(true);
        
        this.dispose();
    }//GEN-LAST:event_btnCloseActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
       
        
        
        for(int i = 0; i  <UIManager.getInstalledLookAndFeels().length; i++){
                //System.out.println(i +"/"+UIManager.getInstalledLookAndFeels().length);
            
                //System.out.println(UIManager.getInstalledLookAndFeels()[i].getName());
        
            
            
              
            //  javax.swing.UIManager.LookAndFeelInfo info  javax.swing.UIManager.getInstalledLookAndFeels() 
            try{
            if("FlatLaFDark".equalsIgnoreCase(UIManager.getInstalledLookAndFeels()[i].getName())){
                //System.out.println(UIManager.getInstalledLookAndFeels()[i].getClassName());
             FlatDarkLaf.setup();
             
          UIManager.setLookAndFeel(UIManager.getInstalledLookAndFeels()[i].getClassName());
          
         // javax.swing.UIManager.setLookAndFeel
                //System.out.println("Class Found");
          
            }
          }catch( ClassNotFoundException e){
              
                //System.out.println("Not Found");
              
          } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DataBaseGUI_MainFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DataBaseGUI_MainFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DataBaseGUI_MainFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
            
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmAddComponent().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnSubmit;
    private com.github.lgooddatepicker.components.DatePicker dpReleaseDate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblDateError;
    private javax.swing.JLabel lblGeneralError;
    private javax.swing.JLabel lblNameError;
    private javax.swing.JSpinner spnPrice;
    private javax.swing.JSpinner spnQuantity;
    private javax.swing.JToggleButton tglSMD;
    private javax.swing.JTextField txtcomponentName;
    // End of variables declaration//GEN-END:variables
}
