package michaelShepstone;



import com.formdev.flatlaf.FlatDarkLaf;
import java.time.*;
import javax.swing.UIManager;
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Michael
 */
public class frmEditComponent extends javax.swing.JFrame {

    /**
     * Creates new form frmEditComponent
     */
    private int componentID = -1;
     public frmEditComponent( ) {
         
         //Set size and location
         setSize(1000, 600);
         setLocation(100, 200);
                
         //Component returnComponent 
        
        initComponents();
        this.setTitle("Electronic Component Manager - Edit Component");
        //hide the error messages from the user
          lblGeneralError.setVisible(false);
        lblDateError.setVisible(false);
        lblNameError.setVisible(false);
    }
     
    public frmEditComponent( Component oldComponent ) {
        
         initComponents();
         this.setTitle("Electronic Component Manager - Edit Component");
         //Set all the data in the ediatable fields to the data from the component to be edited
        dpReleaseDate.setDate(oldComponent.getReleaseDate());
        
       
        tglSMD.setSelected(oldComponent.isSMD());
      if(tglSMD.isSelected()){
            tglSMD.setText("TRUE");
        }else{
            tglSMD.setText("FALSE");
        }
         
         
        spnPrice.setValue(oldComponent.getComponentPrice());
        spnQuantity.setValue(oldComponent.getComponentQuantity());
        txtComponentName.setText(oldComponent.getComponentName());
        componentID = oldComponent.getId();
        
        
        //hide the error messages
           lblGeneralError.setVisible(false);
        lblDateError.setVisible(false);
         lblNameError.setVisible(false);
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        tglSMD = new javax.swing.JToggleButton();
        txtComponentName = new javax.swing.JTextField();
        dpReleaseDate = new com.github.lgooddatepicker.components.DatePicker();
        spnQuantity = new javax.swing.JSpinner();
        spnPrice = new javax.swing.JSpinner();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnSubmit = new javax.swing.JButton();
        lblGeneralError = new javax.swing.JLabel();
        lblNameError = new javax.swing.JLabel();
        lblDateError = new javax.swing.JLabel();
        btnClose = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tglSMD.setText("False");
        tglSMD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tglSMDActionPerformed(evt);
            }
        });

        txtComponentName.setText("Default");
        txtComponentName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtComponentNameActionPerformed(evt);
            }
        });

        spnQuantity.setModel(new javax.swing.SpinnerNumberModel(1, 0, null, 1));

        spnPrice.setModel(new javax.swing.SpinnerNumberModel(0.0d, 0.0d, null, 0.0d));

        jLabel1.setText("Component Name");

        jLabel2.setText("Component Quantity");

        jLabel3.setText("Component Price");

        jLabel4.setText("SMD:");

        jLabel5.setText("Release Date");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(dpReleaseDate, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tglSMD, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtComponentName, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(spnQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(spnPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {dpReleaseDate, spnPrice, spnQuantity, tglSMD, txtComponentName});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtComponentName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(spnQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(spnPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tglSMD))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(dpReleaseDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {dpReleaseDate, spnPrice, spnQuantity, tglSMD, txtComponentName});

        btnSubmit.setText("Submit");
        btnSubmit.setToolTipText("Commit the changes to the databse");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });

        lblGeneralError.setText("There is one or more erros preventing you from submitting");
        lblGeneralError.setForeground(new java.awt.Color(255, 0, 0));

        lblNameError.setText("This must not be left blank");
        lblNameError.setForeground(new java.awt.Color(255, 0, 0));

        lblDateError.setText("This is not a valid date");
        lblDateError.setForeground(new java.awt.Color(255, 0, 0));

        btnClose.setText("Close");
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblDateError)
                            .addComponent(lblNameError)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblGeneralError)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSubmit)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnClose)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(lblNameError)
                        .addGap(118, 118, 118)
                        .addComponent(lblDateError))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSubmit)
                    .addComponent(lblGeneralError)
                    .addComponent(btnClose))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tglSMDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tglSMDActionPerformed
     //If the button is pressed, change the text in order to represent it's state
        
        if(tglSMD.isSelected()){
            tglSMD.setText("TRUE");
        }else{
            tglSMD.setText("FALSE");
        }
    }//GEN-LAST:event_tglSMDActionPerformed

    private void txtComponentNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtComponentNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtComponentNameActionPerformed

    
    
    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed

        //if the submit button is pressed, add the data that the user entered to the database
        
        //Get data from components
        String componentName = txtComponentName.getText();
        int componentQuantity = (int) spnQuantity.getValue();
        double componentPrice = (double) spnPrice.getValue();
        boolean SMD = tglSMD.isSelected();
        LocalDate releaseDate = dpReleaseDate.getDate();

        
        //cereate a component with this data
        Component returnComponent = new Component(componentID, componentName, componentPrice, componentQuantity, SMD, releaseDate);

        
        
        DBmanager db = new DBmanager();
        
        
        //Check for errors
        if(componentName.isBlank()){
                lblNameError.setVisible(true);
                lblGeneralError.setVisible(true);

            }
        else if(releaseDate == null){
                lblDateError.setVisible(true);
                lblGeneralError.setVisible(true);
            }
        
        
     else   if(db.editComponent(returnComponent)){
//if the changes were sucesful, return the user to the main form.
            new DataBaseGUI_MainFrm().setVisible(true);

            this.dispose();}

        else{
         
         //If there was an error, display an error message to the user
            lblGeneralError.setVisible(true);
            

        }

    }//GEN-LAST:event_btnSubmitActionPerformed

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        new DataBaseGUI_MainFrm().setVisible(true);
        
        this.dispose();
    }//GEN-LAST:event_btnCloseActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
       
        
        
        for(int i = 0; i  <UIManager.getInstalledLookAndFeels().length; i++){
            System.out.println(i +"/"+UIManager.getInstalledLookAndFeels().length);
            
            System.out.println(UIManager.getInstalledLookAndFeels()[i].getName());
        
            
            
              
            //  javax.swing.UIManager.LookAndFeelInfo info  javax.swing.UIManager.getInstalledLookAndFeels() 
            try{
            if("FlatLaFDark".equalsIgnoreCase(UIManager.getInstalledLookAndFeels()[i].getName())){
              System.out.println(UIManager.getInstalledLookAndFeels()[i].getClassName());
             FlatDarkLaf.setup();
             
          UIManager.setLookAndFeel(UIManager.getInstalledLookAndFeels()[i].getClassName());
          
         // javax.swing.UIManager.setLookAndFeel
              System.out.println("Class Found");
          
            }
          }catch( ClassNotFoundException e){
              
              System.out.println("Not Found");
              
          } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DataBaseGUI_MainFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DataBaseGUI_MainFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DataBaseGUI_MainFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
            
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmEditComponent().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnSubmit;
    private com.github.lgooddatepicker.components.DatePicker dpReleaseDate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblDateError;
    private javax.swing.JLabel lblGeneralError;
    private javax.swing.JLabel lblNameError;
    private javax.swing.JSpinner spnPrice;
    private javax.swing.JSpinner spnQuantity;
    private javax.swing.JToggleButton tglSMD;
    private javax.swing.JTextField txtComponentName;
    // End of variables declaration//GEN-END:variables
}
